### ISSUE TITLE
Sending email with SMTP

### ISSUE THREAD

**Issue by phemmylintry** [microapidev/email-microapi#3]
Resources: https://sendgrid.com/docs/for-developers/sending-email/django/

**Comment by phemmylintry** [comment]
Done

**Comment by HackinwaleDev** [comment]
I never know SendGrid is allowed sha thought Mark wants MailChimp hahaha

**Comment by phemmylintry** [comment]
Lol, He didnt specify, so we went with sendgrid

**Comment by HackinwaleDev** [comment]
I have always wanted SendGrid. I used it for last FundMyLaptop project while waiting for EmailAPI from another team. It was sleek.

Great job man.
PS: Link to AuthAPI repo pls??
